graphics/py-zbar-py: Some adjustments in MD
  - Add ICONV_LIB to LDFLAGS.
  - Remove graphics/zbar from LIB_DEPENDS (not sure if this is 100% correct).

 The problem is that python3.7-config --cflags has: '... -I/usr/local/include'
 in it, and the build process uses those parameters for the build (presumably
 via setup.py).
 Since /usr/local/include is in the include search path, the first
 zbar.h taken will be the one from graphics/zbar which has different function
 prototype for some functions:

    Source/zbar/img_scanner.c: At top level:
    Source/zbar/img_scanner.c:477:5: error: conflicting types for
    'zbar_scan_image'
     int zbar_scan_image(zbar_image_scanner_t *iscn,
         ^~~~~~~~~~~~~~~
    In file included from Source/zbar/img_scanner.c:34:
    /usr/local/include/zbar.h:1096:12: note: previous declaration of
    'zbar_scan_image' was here
    extern int zbar_scan_image(zbar_image_scanner_t *scanner,
               ^~~~~~~~~~~~~~~

 So instead of messing around with setup.py just do this hack. At least the
 python import seems to work:

    # python3.7
    Python 3.7.9 (default, Sep  9 2020, 10:05:46)
    [GCC 8.3 [DragonFly] Release/2019-02-22] on dragonfly5
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import zbar
    >>>