Fix crash when cpu_count() is called with logical=False.
* Add cpu_count_cores() to list of symbols in _psutil_bsd.c.

Before:

>>> import psutil
>>> psutil.cpu_count()
8
>>> psutil.cpu_count(logical=True)
8
>>> psutil.cpu_count(logical=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/psutil/__init__.py", line 1591, in cpu_count
    ret = _psplatform.cpu_count_cores()
  File "/usr/local/lib/python3.9/site-packages/psutil/_psbsd.py", line 286, in cpu_count_cores
    return cext.cpu_count_cores()
AttributeError: module 'psutil._psutil_bsd' has no attribute 'cpu_count_cores'
>>>

After:

>>> import psutil
>>> psutil.cpu_count()
8
>>> psutil.cpu_count(logical=True)
8
>>> psutil.cpu_count(logical=False)
4
>>>