print/cups-filters: Mark the mess.
This port is very dirty, absolute symlinks, plist problems etc:
===> Staging rc.d startup script(s)
====> Running Q/A tests (stage-qa)
Warning: Bad symlink '/usr/local/bin/foomatic-rip' pointing to an absolute pathname '/usr/local/libexec/cups/filter/foomatic-rip'
--------------------------------------------------------------------------------
--  Phase: check-plist
--------------------------------------------------------------------------------
====> Checking for pkg-plist issues (check-plist)
===> Parsing plist
===> Checking for items in STAGEDIR missing from pkg-plist
Error: Orphaned: /etc/init.d/cups-browsed
Error: Orphaned: /etc/rc0.d/K00cups-browsed
Error: Orphaned: /etc/rc2.d/K00cups-browsed
Error: Orphaned: /etc/rc2.d/S99cups-browsed
Error: Orphaned: /etc/rc3.d/K00cups-browsed
Error: Orphaned: /etc/rc3.d/S99cups-browsed
Error: Orphaned: /etc/rc5.d/K00cups-browsed
Error: Orphaned: /etc/rc5.d/S99cups-browsed
Error: Orphaned: @dir /etc/init.d
Error: Orphaned: @dir /etc/rc0.d
Error: Orphaned: @dir /etc/rc2.d
Error: Orphaned: @dir /etc/rc3.d
Error: Orphaned: @dir /etc/rc5.d
===> Checking for items in pkg-plist which are not in STAGEDIR
===> Error: Plist issues found.
*** Error code 1
As for libgcc_pic.a + c++ + ld.gold looks like binutils issue.