news/nntp: Regen patches after ansi patches.
synth test fails:
===> Checking for items in STAGEDIR missing from pkg-plist
Error: Orphaned: @dir %%VARBASE%%/%%NEWSCTL%%
Error: Orphaned: @dir %%VARBASE%%/lib