www/qt6-webengine: more patches, build still broken
 There is a linking error:

   /usr/local/bin/ld: CMakeFiles/qwebengine_convert_dict.dir/main.cpp.o: undefined reference to symbol '_ZdlPv@@GLIBCXX_3.4'
   /usr/local/bin/ld: /usr/local/lib/gcc11/libstdc++.so.6: error adding symbols: DSO missing from command line
   clang-15: error: linker command failed with exit code 1 (use -v to see invocation)

 Since we're building with clang and other QT6 libraries are built with GCC11, there are missing
 unresolved symbols. And we cannot use libstdc++ for linking since we're using libc++

 Next step would probably be trying to build all the qt6 components with clang.