math/py-pandas: Revert an upstream commit that broke the build.
 - Pandas not only removed upstream a fix for MSVC but also removed what
   allowed us to have working std::signbit, see:
     https://github.com/pandas-dev/pandas/pull/45008
 - Revert that commit partially so that we fix the build error:
     pandas/_libs/window/aggregations.cpp:4951:18: error: 'signbit' was
     not declared in this scope