devel/abseil: Make it build without 'USES+= alias'
  - Build with the default LLVM due to the error:

      error: braces around scalar initializer for type [...]

  - Patch config.h to disable ABSL_INTERNAL_USE_NONPROD_MUTEX
    which was causing issues with other ports like 'devel/gprc'